export enum CAL_ACTIONS {
  // boolean payloads
  IS_LOADING,
  SET_ERROR,
  SET_CAL_NAME,
  SET_CAL_ID,
  SET_CAL_LINK,
  SET_CAL_CLOSE_TIME,
  SET_CAL_START_TIME,
  SET_CAL_WORK_WEEK,
  SET_CAL_SCHEDULE,
  SET_CAL_SELECTED_DAY,
  SET_CAL_EVENTS,
  SET_THEME,
  SET_CAL_MEETING,
  SET_EVENT,
  SET_REQUEST_STATUS,
}
